/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maze_v4.ViewComponents;

import java.awt.Graphics;
import maze_v4.DataModel;
import maze_v4.Interfaces.IMazeRenderer;
import maze_v4.Renderers.SquareMazeRenderer;
import maze_v4.SquareMaze.SquareMazeStructure;

/**
 *
 * @author dean
 */
public class MazePanel extends javax.swing.JPanel
{
    IMazeRenderer mazeRenderer;
    DataModel dataModel;
    /**
     * Creates new form MazePanel
     */
    public MazePanel()
    {
        initComponents();
        
        this.dataModel = DataModel.getInstance();
        
        //  Replace with factory...
        this.mazeRenderer = new SquareMazeRenderer((SquareMazeStructure)dataModel.getMazeStructure());
        
    }

    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        
        g.drawImage(mazeRenderer.drawMaze(), 0, 0, this);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
